/**
 * Test fixture paths for Squoosh test suite.
 *
 * This module exports paths to all test fixture images generated by
 * generate-fixtures.js. Import these paths in your tests to access
 * the test images.
 *
 * @example
 * ```typescript
 * import { FIXTURES } from '../test-fixtures';
 *
 * const image = await fs.readFile(FIXTURES.smallRgb);
 * ```
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const IMAGES_DIR = path.join(__dirname, 'images');

/**
 * Paths to all test fixture images.
 */
export const FIXTURES = {
  // Small images (100x100) - for unit tests
  /** 100x100 solid red PNG (RGB, no alpha) */
  smallRgb: path.join(IMAGES_DIR, 'small-rgb.png'),
  /** 100x100 semi-transparent blue PNG (RGBA) */
  smallRgba: path.join(IMAGES_DIR, 'small-rgba.png'),
  /** 100x100 solid green JPEG */
  smallJpg: path.join(IMAGES_DIR, 'small.jpg'),
  /** 100x100 solid yellow WebP */
  smallWebp: path.join(IMAGES_DIR, 'small.webp'),
  /** 100x100 solid magenta GIF */
  smallGif: path.join(IMAGES_DIR, 'small.gif'),

  // Medium images (800x600) - for integration tests
  /** 800x600 gradient pattern JPEG */
  mediumJpg: path.join(IMAGES_DIR, 'medium.jpg'),
  /** 800x600 detailed pattern PNG with alpha */
  mediumPng: path.join(IMAGES_DIR, 'medium.png'),

  // Test pattern images
  /** 256x256 color gradient PNG for quality testing */
  gradient: path.join(IMAGES_DIR, 'gradient.png'),
  /** 200x200 black/white checkerboard PNG for compression artifact detection */
  checkerboard: path.join(IMAGES_DIR, 'checkerboard.png'),

  // Edge case images
  /** 1x1 pixel white PNG */
  tiny: path.join(IMAGES_DIR, 'tiny.png'),
  /** 1000x10 horizontal gradient PNG (very wide) */
  wide: path.join(IMAGES_DIR, 'wide.png'),
  /** 10x1000 vertical gradient PNG (very tall) */
  tall: path.join(IMAGES_DIR, 'tall.png'),
} as const;

/**
 * Type representing all fixture keys.
 */
export type FixtureKey = keyof typeof FIXTURES;

/**
 * Get fixture path by key.
 * @param key - The fixture key
 * @returns The absolute path to the fixture image
 */
export function getFixturePath(key: FixtureKey): string {
  return FIXTURES[key];
}

/**
 * Get all fixture paths as an array.
 * @returns Array of all fixture file paths
 */
export function getAllFixturePaths(): string[] {
  return Object.values(FIXTURES);
}

/**
 * Directory containing all fixture images.
 */
export const FIXTURES_DIR = IMAGES_DIR;

/**
 * Fixture metadata for testing purposes.
 */
export const FIXTURE_METADATA = {
  smallRgb: { width: 100, height: 100, channels: 3, format: 'png' },
  smallRgba: { width: 100, height: 100, channels: 4, format: 'png' },
  smallJpg: { width: 100, height: 100, channels: 3, format: 'jpeg' },
  smallWebp: { width: 100, height: 100, channels: 3, format: 'webp' },
  smallGif: { width: 100, height: 100, channels: 3, format: 'gif' },
  mediumJpg: { width: 800, height: 600, channels: 3, format: 'jpeg' },
  mediumPng: { width: 800, height: 600, channels: 4, format: 'png' },
  gradient: { width: 256, height: 256, channels: 3, format: 'png' },
  checkerboard: { width: 200, height: 200, channels: 3, format: 'png' },
  tiny: { width: 1, height: 1, channels: 3, format: 'png' },
  wide: { width: 1000, height: 10, channels: 3, format: 'png' },
  tall: { width: 10, height: 1000, channels: 3, format: 'png' },
} as const;

/**
 * Type for fixture metadata.
 */
export type FixtureMetadata = (typeof FIXTURE_METADATA)[FixtureKey];
