/**
 * Test fixture paths for Squoosh test suite.
 *
 * This module exports paths to all test fixture images generated by
 * generate-fixtures.js. Import these paths in your tests to access
 * the test images.
 *
 * @example
 * ```typescript
 * import { FIXTURES } from '../test-fixtures';
 *
 * const image = await fs.readFile(FIXTURES.smallRgb);
 * ```
 */
/**
 * Paths to all test fixture images.
 */
export declare const FIXTURES: {
    /** 100x100 solid red PNG (RGB, no alpha) */
    readonly smallRgb: string;
    /** 100x100 semi-transparent blue PNG (RGBA) */
    readonly smallRgba: string;
    /** 100x100 solid green JPEG */
    readonly smallJpg: string;
    /** 100x100 solid yellow WebP */
    readonly smallWebp: string;
    /** 100x100 solid magenta GIF */
    readonly smallGif: string;
    /** 800x600 gradient pattern JPEG */
    readonly mediumJpg: string;
    /** 800x600 detailed pattern PNG with alpha */
    readonly mediumPng: string;
    /** 256x256 color gradient PNG for quality testing */
    readonly gradient: string;
    /** 200x200 black/white checkerboard PNG for compression artifact detection */
    readonly checkerboard: string;
    /** 1x1 pixel white PNG */
    readonly tiny: string;
    /** 1000x10 horizontal gradient PNG (very wide) */
    readonly wide: string;
    /** 10x1000 vertical gradient PNG (very tall) */
    readonly tall: string;
};
/**
 * Type representing all fixture keys.
 */
export type FixtureKey = keyof typeof FIXTURES;
/**
 * Get fixture path by key.
 * @param key - The fixture key
 * @returns The absolute path to the fixture image
 */
export declare function getFixturePath(key: FixtureKey): string;
/**
 * Get all fixture paths as an array.
 * @returns Array of all fixture file paths
 */
export declare function getAllFixturePaths(): string[];
/**
 * Directory containing all fixture images.
 */
export declare const FIXTURES_DIR: string;
/**
 * Fixture metadata for testing purposes.
 */
export declare const FIXTURE_METADATA: {
    readonly smallRgb: {
        readonly width: 100;
        readonly height: 100;
        readonly channels: 3;
        readonly format: "png";
    };
    readonly smallRgba: {
        readonly width: 100;
        readonly height: 100;
        readonly channels: 4;
        readonly format: "png";
    };
    readonly smallJpg: {
        readonly width: 100;
        readonly height: 100;
        readonly channels: 3;
        readonly format: "jpeg";
    };
    readonly smallWebp: {
        readonly width: 100;
        readonly height: 100;
        readonly channels: 3;
        readonly format: "webp";
    };
    readonly smallGif: {
        readonly width: 100;
        readonly height: 100;
        readonly channels: 3;
        readonly format: "gif";
    };
    readonly mediumJpg: {
        readonly width: 800;
        readonly height: 600;
        readonly channels: 3;
        readonly format: "jpeg";
    };
    readonly mediumPng: {
        readonly width: 800;
        readonly height: 600;
        readonly channels: 4;
        readonly format: "png";
    };
    readonly gradient: {
        readonly width: 256;
        readonly height: 256;
        readonly channels: 3;
        readonly format: "png";
    };
    readonly checkerboard: {
        readonly width: 200;
        readonly height: 200;
        readonly channels: 3;
        readonly format: "png";
    };
    readonly tiny: {
        readonly width: 1;
        readonly height: 1;
        readonly channels: 3;
        readonly format: "png";
    };
    readonly wide: {
        readonly width: 1000;
        readonly height: 10;
        readonly channels: 3;
        readonly format: "png";
    };
    readonly tall: {
        readonly width: 10;
        readonly height: 1000;
        readonly channels: 3;
        readonly format: "png";
    };
};
/**
 * Type for fixture metadata.
 */
export type FixtureMetadata = (typeof FIXTURE_METADATA)[FixtureKey];
//# sourceMappingURL=index.d.ts.map